FROM nginx:1.17.1-alpine
COPY *.txt /usr/share/nginx/html
COPY *.ico /usr/share/nginx/html
COPY *.html /usr/share/nginx/html
COPY *.js /usr/share/nginx/html/
COPY *.css /usr/share/nginx/html
COPY ./assets /usr/share/nginx/html/assets/
